FROM openjdk:11-jdk

# install python3 && python3-pip
RUN apt-get update \
    && apt-get install -y python3 python3-pip jq && pip3 install --upgrade pip \
    && pip install --upgrade awscli

RUN echo "${JAVA_HOME}" && \
    java --version

ENV GRADLE_VERSION "7.4.2"
ENV PATH $PATH:/usr/local/gradle-${GRADLE_VERSION}/bin
RUN URL=https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip && \
    wget -O /tmp/gradle.zip $URL && \
    unzip -d /usr/local /tmp/gradle.zip && \
    rm -rf /tmp/gradle.zip

# Install Android SDK Tools
ENV ANDROID_HOME "/usr/local/android-sdk"
ENV ANDROID_SDK_ROOT $ANDROID_HOME
ENV CMDLINE_TOOLS_ROOT "${ANDROID_HOME}/cmdline-tools/latest/bin"
ENV ADB_INSTALL_TIMEOUT 120
ENV PATH "${ANDROID_HOME}/emulator:${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/platform-tools/bin:${PATH}"
RUN SDK_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip" && \
	mkdir -p ${ANDROID_HOME}/cmdline-tools && \
	mkdir ${ANDROID_HOME}/platforms && \
	mkdir ${ANDROID_HOME}/ndk && \
	wget -O /tmp/cmdline-tools.zip -t 5 "${SDK_TOOLS_URL}" && \
	unzip -q /tmp/cmdline-tools.zip -d ${ANDROID_HOME}/cmdline-tools && \
	rm /tmp/cmdline-tools.zip && \
	mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest

RUN echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "tools" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platform-tools" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "build-tools;32.0.0"         

RUN echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-Tiramisu" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-32" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-31" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-30" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-29" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-28" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-27" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-26" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-25" && \
	echo y | ${CMDLINE_TOOLS_ROOT}/sdkmanager "platforms;android-24"
