version: '3'

services:
  kafka:
    image: wurstmeister/kafka:${KAFKA_VERSION}
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_LOG_DIRS: /kafka
      KAFKA_CREATE_TOPICS: ${KAFKA_DEFAULT_CREATE_TOPICS}:3:1
      KAFKA_MESSAGE_MAX_BYTES: ${KAFKA_MESSAGE_MAX_BYTES}
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: ${KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS}
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 30000
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    ports:
        - "2181:2181"
